### ISSUE TITLE
Hydra::Works::CharacterizationService placing metadata on FileSet instead of File

### ISSUE THREAD

**Issue by awead** [projecthydra/hydra-works#290]
This issue was first reported in projecthydra/sufia#1894

Hydra::Works::CharacterizationService is updating the FileSet object with technical metadata extracted from Fits. This data should go in the File object instead.

**Comment by awead** [comment]
In looking into this, it's going deeper. `Hydra::Works::CharacterizationService` takes an `ActiveFedora::Base` object, but it needs to take a `Hydra::PCDM::File`. We'd need to re-tool Hydra::Works to apply the various schemas to that object, similar to how it's being done in Hydra::PCDM:

https://github.com/projecthydra-labs/hydra-pcdm/blob/master/lib/hydra/pcdm/models/file.rb

**Comment by scossu** [comment]
Is the plan to use the default Fedora fcr:metadata resource to store all technical metadata for a bitstream, or a different resource?

**Comment by mjgiarlo** [comment]
@scossu Yes, the plan is to use `fcr:metadata`.

**Comment by awead** [comment]
Fixed in 6e0dd6cc27ea64af816049b936515a4ef62ddc9b
